dependencies {
    // Registrate & Configuration
    compileOnly("com.tterrag.registrate:Registrate:${registrate_version}")
    compileOnly("dev.toma.configuration:configuration-${minecraft_version}:${configuration_version}")

    // JEI
//    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
//    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    // EMI
    compileOnly("dev.emi:emi-neoforge:${emi_version}:api")
    runtimeOnly("dev.emi:emi-neoforge:${emi_version}")

    // KubeJS & Rhino
    implementation("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")
    implementation("dev.latvian.mods:rhino:${rhino_version}")

    // TFC, Patchouli
    implementation("vazkii.patchouli:Patchouli:${patchouli_version}")
    implementation("curse.maven:terrafirmacraft-302973:${tfc_version}")

    // Beneath
    implementation("curse.maven:beneath-1113980:${beneath_version}")

    // AFC, Firmalife
    implementation("maven.modrinth:arborfirmacraft-(afc):${afc_version}-1.21")
    implementation("maven.modrinth:firmalife:${firmalife_version}")

    // Jade
    implementation("maven.modrinth:jade:${jade_version}+neoforge")

    // GTM & MUI
    implementation("brachy.modularui:modularui-mc1.21.1:${mui_version}")
    implementation("com.gregtechceu.gtceu:gtceu-${minecraft_version}:${gtm_version}")

    // AE2 & GuideME
    implementation("org.appliedenergistics:appliedenergistics2:${ae2_version}")
    implementation("org.appliedenergistics:guideme:${guideme_version}")

    // Create, Ponder, Flywheel
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")

    // Curios, Malum, Lodestone
    implementation("top.theillusivec4.curios:curios-neoforge:${curios_version}+${minecraft_version}")
    implementation("com.sammy.malum:malum:${minecraft_version}-${malum_version}") { transitive = false }
    implementation("team.lodestar.lodestone:lodestone:${minecraft_version}-${lodestone_version}")

    // Eidolon Repraised
    implementation("com.alexthw.eidolon_repraised:eidolon_repraised-${minecraft_version}:${eidolon_version}") { transitive = false }

    // Embers Re-Ignited
    implementation("curse.maven:embers-re-ignited-1579725:${embers_version}")
}