dependencies {
    // Registrate & Configuration
    compileOnly("com.tterrag.registrate:Registrate:${registrate_version}")
    compileOnly("dev.toma.configuration:configuration-${minecraft_version}:${configuration_version}")

    // JEI
//    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
//    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
//    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    // EMI
    compileOnly("dev.emi:emi-neoforge:${emi_version}:api")
    runtimeOnly("dev.emi:emi-neoforge:${emi_version}")

    // TFC, Patchouli
    implementation("vazkii.patchouli:Patchouli:$patchouli_version")
    implementation("curse.maven:terrafirmacraft-302973:${tfc_version}")

    // Jade
    implementation("curse.maven:jade-324717:$jade_version")

    // GTM & MUI
    implementation("brachy.modularui:modularui-mc1.21.1:${mui_version}")
    implementation("com.gregtechceu.gtceu:gtceu-${minecraft_version}:${gtm_version}")

    // Create, Ponder, Flywheel
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")

    // Datagen SourceSet
    dataImplementation("curse.maven:terrafirmacraft-302973:${tfc_version}")
}