name: "Project Build"
run-name: "Project Build #${{ github.run_number }}"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'gradle/**'
      - 'src/**'
      - '*.gradle'
      - 'gradle.properties'
      - 'CHANGELOG.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  info:
    name: "Project Info"
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.fork }}
    outputs:
      name: ${{ steps.check.outputs.name }}
      version: ${{ steps.check.outputs.version }}
      version_type: ${{ steps.check.outputs.version_type }}
      full_name: ${{ steps.check.outputs.name }}-${{ steps.check.outputs.version }}

      loaders: ${{ steps.check.outputs.loaders }}
      game_versions: ${{ steps.check.outputs.game_versions }}
      java_version: ${{ steps.check.outputs.java_version }}

      make_release: ${{ steps.check.outputs.make_release }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: "Check required files and folders"
        uses: andstor/file-existence-action@v3.1.0
        with:
          fail: true
          ignore_case: true
          files: "gradle.properties, build.gradle, LICENSE, README.md, src"

      - name: "Get Project Info"
        id: project_info
        uses: madhead/read-java-properties@latest
        with:
          file: gradle.properties
          all: true

      - name: "Check if tag exists"
        uses: mukunku/tag-exists-action@v1.7.0
        id: tag_check
        with:
          tag: ${{ steps.project_info.outputs.mod_version }}

      - name: "Check"
        id: check
        shell: bash
        run: |
          
          # Get data from previous steps
          TAG_EXISTS="${{ steps.tag_check.outputs.exists }}"
          PROJECT_NAME="${{ steps.project_info.outputs.mod_name }}"
          GAME_VERSIONS="${{ steps.project_info.outputs.minecraft_version }}"
          JAVA_VERSION="${{ steps.project_info.outputs.java_version }}"
          LOADERS="${{ steps.project_info.outputs.loader }}"
          LOADERS_VERSION="${{ steps.project_info.outputs.neo_version }}"

          # Preparation
          IS_RELEASE_CANDIDATE="false"
          if [[ "$TAG_EXISTS" == "false" && -n "${{ steps.project_info.outputs.mod_version }}" ]]; then
            IS_RELEASE_CANDIDATE="true"
          fi

          if [[ "$IS_RELEASE_CANDIDATE" == "true" ]]; then
            PROJECT_VERSION="${{ steps.project_info.outputs.mod_version }}"
            PROJECT_VERSION_TYPE="${{ steps.project_info.outputs.mod_version_type }}"
          else
            PROJECT_VERSION="${{ steps.project_info.outputs.mod_version }}-build-${{ github.run_number }}"
            PROJECT_VERSION_TYPE="Unreleased"
          fi

          # Save values for next steps
          echo "game_version=$GAME_VERSIONS" >> $GITHUB_OUTPUT
          echo "java_version=$JAVA_VERSION" >> $GITHUB_OUTPUT
          echo "loaders=$LOADERS" >> $GITHUB_OUTPUT
          echo "loaders_version=$LOADERS_VERSION" >> $GITHUB_OUTPUT
          echo "name=$PROJECT_NAME" >> $GITHUB_OUTPUT
          echo "version=$PROJECT_VERSION" >> $GITHUB_OUTPUT
          echo "version_type=$PROJECT_VERSION_TYPE" >> $GITHUB_OUTPUT
          echo "exists=$TAG_EXISTS" >> $GITHUB_OUTPUT
          echo "make_release=$IS_RELEASE_CANDIDATE" >> $GITHUB_OUTPUT

      - name: "Generate Build Summary"
        uses: WcAServices/markdown-template-action@v1.1.1
        with:
          template: |
            ## Build Information

            ### Project Info
            | Parameter | Value |
            |-----------|-------|
            | **Name** | `${{ steps.check.outputs.name }}` |
            | **Version** | `${{ steps.check.outputs.version }}` |
            | **Release Type** | `${{ steps.check.outputs.version_type }}` |
            | **Game Versions** | `${{ steps.check.outputs.game_version }}` |
            | **Loaders** | `${{ steps.check.outputs.loaders }}` |
            | **Loaders Version** | `${{ steps.check.outputs.loaders_version }}` |

            ### Build Decision
            | Parameter | Value |
            |-----------|-------|
            | **Tag Exists** | `${{ steps.check.outputs.exists }}` |
            | **Make Release** | `${{ steps.check.outputs.make_release }}` |

  build:
    name: "Build Project"
    needs: [ info ]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7

      - name: "Replace"
        shell: bash
        run: |
          VERSION="${{ needs.info.outputs.version }}"
          if [ ! -f gradle.properties ]; then
            echo "::error::gradle.properties not found"
            exit 1
          fi
          sed -i "s/^mod_version[[:space:]]*=.*/mod_version = ${VERSION}/g" gradle.properties

      - name: "Setup Java"
        uses: actions/setup-java@v5.7.0
        with:
          distribution: 'temurin'
          java-version: ${{ needs.info.outputs.java_version }}
          cache: 'gradle'

      - name: "Prepare artifact"
        run: |
          chmod +x gradlew
          ./gradlew build
          ls -la build/libs/

      - name: "Upload artifact"
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ needs.info.outputs.full_name }}
          path: build/libs/${{ needs.info.outputs.full_name }}.jar
          if-no-files-found: error

  release:
    name: "Release"
    needs: [ info, build ]
    runs-on: ubuntu-latest
    if: ${{ needs.info.outputs.make_release == 'true' }}

    steps:
      - name: "Debug make_release"
        run: |
          echo "make_release = '${{ needs.info.outputs.make_release }}'"
          echo "Comparison result: ${{ needs.info.outputs.make_release == 'true' }}"

      - name: "Download artifact"
        uses: actions/download-artifact@v8

      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.info.outputs.version }}
          name: Release ${{ needs.info.outputs.version }}
          files: build/libs/${{ needs.info.outputs.full_name }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Extract changelog section"
        id: changelog
        shell: bash
        run: |
          VERSION=${{ needs.info.outputs.version }}

          awk "/## \[$VERSION\]/ {flag=1; next} /## \[/ && flag==1 {flag=0} flag" changelog.md > changelog.txt

          echo "text<<EOF" >> $GITHUB_OUTPUT
          cat changelog.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT